# Generated by Django 5.2.2 on 2025-06-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_image_category_is_featured'),
        ('users', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='products.productvariant', verbose_name='Избранные варианты товаров'),
        ),
    ]
