# Generated by Django 5.2.2 on 2025-06-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_paid_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_checkout_session_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
    ]
